# Generated by Django 3.2.25 on 2024-11-11 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oil_loss', '0002_transaction_natural_loss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='natural_loss',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oil_loss.storage', verbose_name='Хранилище'),
        ),
    ]
